# Add label to changes to any file in the docs folder
Site File:
- changed-files:
  - any-glob-to-any-file: 'docs/**'

# Add 'source' label to any change to src files within the source dir EXCEPT for the docs sub-folder
Source File:
- all:
  - changed-files:
    - any-glob-to-any-file: '**'
    - all-globs-to-all-files: '!docs/**'

Test:
- changed-files:
  - any-glob-to-any-file: '**'
  if: [[ 1 == 2 ]]

# Add 'AnyChange' label to any changes within the entire repository
Any Change:
- changed-files:
  - any-glob-to-any-file: '**'
