site_name: Terror i Sverige
theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Byt till mörkt tema
      primary: deep purple
      accent: deep purple

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Byt till ljust tema
      primary: black
      accent: deep purple
