name: Build MkDocs Site

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  CheckChanges:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3
    # Test building the site in strict mode
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v41
    - name: Check changed file authors
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        for file in "$ALL_CHANGED_FILES"; do
          echo "$file was changed"
        done
  Test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    # Install python modules
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    # Test building the site in strict mode
    - name: Test MkDocs
      run: |
        mkdocs build --strict --clean --site-dir test_build
    # Build the site to the _site dir
  Build:
    needs: Test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    # Install python modules
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    # Test building the site in strict mode
    - name: Test MkDocs
      run: |
        mkdocs build --strict --clean --site-dir test_build
    # Build the site to the _site dir
    - name: Build MkDocs
      run: |
        mkdocs build --site-dir _site
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v2
  Deploy:
    # Add a dependency to the build job
    needs: Build
    if: github.ref == 'refs/heads/main'

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

